### PR TITLE
fix retargeting

### PR DESCRIPTION
**Pull request by gnarf**
after using `.retarget()` the code for the autocomplete filtering was wrong.

I updated this to work

### CODE REVIEW

**Comment by bobholt** [comment]
:+1:

**Comment by gnarf** [comment]
Did I get something wrong here or did you fix this bug already a different way?

**Comment by gnarf** [comment]
Oh I see you realised a 4.0, I'll try an upgrade!

**Comment by bevacqua** [comment]
I think this is working now

**Comment by bevacqua** [comment]
Sorry for not commenting!

**Comment by bevacqua** [comment]
Please do check if it's still broken and if it is feel free to submit a new PR. The codebase is in ES6 now, tho, so it's a bit different.

**Pull request closed without merging**
