### PR TITLE
Support live suggestions

### PR DESCRIPTION
**Pull request by stefanoverna**
The function passed as `options.suggestions` is now called at every input value change.

### CODE REVIEW

**Comment by stefanoverna** [comment]
This should hopefully fix #24. The only change to the API is that the `options.suggestions` function now takes two parameters, the first being the current input value.

**Comment by stefanoverna** [comment]
@bevacqua, let me know how can I improve the PR

**Comment by TehShrike** [comment]
I am looking for a reasonable autocomplete, and horsey looks quite reasonable.  I need live loading, though, so I'll pull down this pull request and test with it.

**Comment by TehShrike** [comment]
I've been using this feature [in my horsey fork](https://github.com/bevacqua/horsey/compare/master...TehShrike:features-i-need?expand=1) and it's been working great so far.  I'd love to see this get merged.

**Comment by stefanoverna** [comment]
glad it helped, @TehShrike! :)

**Comment by TehShrike** [comment]
Out of curiosity @stefanoverna are you still using horsey in any projects?  Are you maintaining a fork with this feature yet?

**Comment by TehShrike** [comment]
I did make one fix to an issue where selection of the first item was being lost: https://github.com/stefanoverna/horsey/pull/1

**Comment by whatda** [comment]
Seems to work fine, thanks. One thing I noticed though is that one request per input keyup seems a bit overkill in some scenarios, especially if the user is typing really quickly. Maybe a stop in case of pending requests would be nice.

**Comment by TehShrike** [comment]
A debouncer would be nice, though it could probably be applied as easily in the callback by the consumer.

**Pull request merged**
