### PR TITLE
Add config options to change class names in generated markup

### PR DESCRIPTION
**Pull request by thompsongl**
Allows for optionally specifying the class names that will be applied to the dropdown list `ul` and its children elements.
Helpful for incorporating horsey into projects with strict CSS naming conventions and linting, or using utility/functional class-based CSS systems (e.g., http://tachyons.io/).

I'm happy to update the readme "Options" documentation also if this is something you'd like to merge.

### CODE REVIEW

**Comment by TehShrike** [comment]
+1

**Comment by TehShrike** [comment]
I've been using this feature [in my horsey fork](https://github.com/bevacqua/horsey/compare/master...TehShrike:features-i-need?expand=1) and it's been working great so far.  I'd love to see this get merged.

**Comment by meodai** [comment]
me to :+1:

**Comment by bevacqua** [comment]
Please rebase and document.

**Comment by thompsongl** [comment]
There's been significant changes to the source since I originally opened this, and I no longer have a project using the new features. Feel free to close the PR and I will reopen if needed, or someone else (@TehShrike) is welcome to pick up where I left off.

**Comment by TehShrike** [comment]
Do you prefer `dist` files being included in pull requests, or would you rather generate them yourself @bevacqua ?

**Comment by bevacqua** [comment]
They're generated as part of releases

**Comment by bevacqua** [comment]
`npm run build` does this, `npm run deploy` does `npm run build`

**Pull request closed without merging**
