### PR TITLE
Lazy render feature

### LINKED ISSUE #13: Performance for large datasets
I noticed that the implementation for the hide/show is just adding a class `sey-hide`.
This can get really slow for large datasets because changing the DOM is quite slow.
It also flashes the entire list upon typing the first letter before hiding items in the list that match.
I believe the performance can be improved dramatically if you do lazy rendering of the items such as [select2](https://github.com/select2/select2) or [slickgrid](https://github.com/mleibman/SlickGrid).

The downside would be a rigid height for each item in the list in order to calculate the position when scrolling. Maybe we can ignore the scrolling and instead switch to lazy rendering if a `limit` is imposed.
I can create a jsfiddle with an example of 1000+ items and then see if a lazy rendering solution performs better.

Are you interested or is this outside the scope of horsey?

### PR DESCRIPTION
**Pull request by styfle**
Enable lazy rendering for list items `li` to better support large datasets.
Fixes #13

### CODE REVIEW

**Comment by styfle** [comment]
@bevacqua Did you get a chance to try this out?
Also, are there any automated tests?

**Comment by styfle** [comment]
/cc @RoryDH @Hurtak @domchristie 
Trying to get some more eyes on this since it's a big change.

**Comment by bevacqua** [comment]
Haven't had the time, and this is a huge changeset. Might be a while before I can take a look

**Comment by styfle** [comment]
@bevacqua That's fine.
I found [At.js](https://github.com/ichord/At.js) that does lazy rendering and works very similar to horsey so I'm going with that solution.

**Pull request closed without merging**
