### PR TITLE
Fix suggestions with type number

### LINKED ISSUE #6: Suggestions with type number are converted to undefined
```js
horsey(document.getElementById('test'), {
	suggestions: ['aaa', 100, 200, 300]
});
```

will produce

http://i.imgur.com/QlqbUmr.png

### PR DESCRIPTION
**Pull request by Hurtak**
- tested it on the demo page examples, seems to work fine
- used `String()` for retyping for its clarity, if you prefer different style like `var + ''` or we really care about performance (`String()` seem to be about 20% slower), I can update PR
- closes #6

### CODE REVIEW

**Comment by bevacqua** [comment]
If `suggestion` is `null` this will throw an error.

**Comment by Hurtak** [comment]
Should be fixed now

**Comment by bevacqua** [comment]
Let's just use `'value' in suggestion ? suggestion.value : suggestion` and the same for `text`

**Comment by Hurtak** [comment]
That would throw type error on anything other than arrays and objects

**Comment by bevacqua** [comment]
Resolved in `2.5.2`

**Pull request closed without merging**
